---
- name: Playbook to launch a website
  hosts: sarath
  become: true
  tasks:
    - name: install apache2
      apt:
        name: ["apache2"]
        state: present
        update_cache: yes
    - name: update code
      copy:
        src: /home/ubuntu/playbooks/index.html
        dest: /var/www/html/
    - name: restart apache2
      service:
        name: apache2
        state: restarted
