---
- name: write a playbook to install a package default-jdk. If package name is not default-jdk, donot run the task
  hosts: all
  vars:
    og_package: default-jdk
  vars_prompt:
    - name: package_name
      prompt:  "Enter package name you want to install"
  become: true
  tasks:
    - name: install package
      apt:
        name: "{{ package_name }}"
        state: present
        update_cache: yes
      when:
        package_name==og_package
...
